# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Master Degree\Lesson\web crawler\Project\gui\Indexing_note.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MW_IDX_Note(object):
    def setupUi(self, MW_IDX_Note):
        MW_IDX_Note.setObjectName("MW_IDX_Note")
        MW_IDX_Note.resize(311, 600)
        self.centralwidget = QtWidgets.QWidget(MW_IDX_Note)
        self.centralwidget.setObjectName("centralwidget")
        self.tb_IDX_show = QtWidgets.QTableWidget(self.centralwidget)
        self.tb_IDX_show.setGeometry(QtCore.QRect(0, 0, 311, 551))
        self.tb_IDX_show.setColumnCount(0)
        self.tb_IDX_show.setObjectName("tb_IDX_show")
        self.tb_IDX_show.setRowCount(0)
        self.tb_IDX_show.horizontalHeader().setDefaultSectionSize(85)
        MW_IDX_Note.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MW_IDX_Note)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 311, 21))
        self.menubar.setObjectName("menubar")
        MW_IDX_Note.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MW_IDX_Note)
        self.statusbar.setObjectName("statusbar")
        MW_IDX_Note.setStatusBar(self.statusbar)

        self.retranslateUi(MW_IDX_Note)
        QtCore.QMetaObject.connectSlotsByName(MW_IDX_Note)

    def retranslateUi(self, MW_IDX_Note):
        _translate = QtCore.QCoreApplication.translate
        MW_IDX_Note.setWindowTitle(_translate("MW_IDX_Note", "note"))
